version: '3'

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local